### ISSUE TITLE
Potential speedup

### ISSUE THREAD

**Issue by TimTaylor** [fragla/eq5d#13]
Looking at the `eq5d5l()` and `eq5d3l()` functions I think there's an opportunity to speed the code up a little with a relatively small change. The idea would be to change from using a single column data frame for the survey to using a named vector. This would then avoid the overhead of multiple calls to `[.data.frame` when calling the `eq5d()` function.

In `eq5d5l()` we could change the following line https://github.com/fragla/eq5d/blob/f8535647921cabdded16db055a3bb436aca5677c/R/eq5d5l.R#L28
to instead be
```
survey <- setNames(survey[[country]], rownames(survey))
```
Subsequent lines can then be changed to extract from this vector rather than the data frame (this just entails the removal of a few commas in some of the internal functions). Quickly trialling the suggested change I saw the following increase in speed:

``` r
# Example data
scores.df <- data.frame(MO=c(1,2,3,4,5), SC=c(1,5,4,3,2), UA=c(1,5,2,3,1), PD=c(1,3,4,3,4), AD=c(1,2,NA,2,1))
scores.df2 <- do.call(rbind, replicate(200,scores.df,FALSE))
countries <- names(VT)

# The current development version
system.time(
  lapply(countries, eq5d, scores=scores.df2, version="5L", type="VT", ignore.invalid=TRUE)
)
#>    user  system elapsed 
#>   4.728   0.003   4.749

# Trialing the suggested change
system.time(
  lapply(countries, beq5d, scores=scores.df2, version="5L", type="VT", ignore.invalid=TRUE)
)
#>    user  system elapsed 
#>   2.041   0.002   2.050
```

If you think this is a good idea then I'm happy to provide a patch. For reference this only really became apparent when testing across multiple value sets on some larger data (for smaller data or using individual value sets the change is unlikely to be noticeable).

**Comment by fragla** [comment]
I think that'd be great. Please do submit the patch.
