### ISSUE TITLE
Feature Request: NZ Value Set

### ISSUE THREAD

**Issue by jiro-ishida** [fragla/eq5d#18]
Hi there, 

Would it be possible to include the New Zealand value set from this research in the next release?

https://www.1000minds.com/sectors/health/hrqol/eq-5d

**Comment by fragla** [comment]
Shouldn't be a problem. I'll see if I can add it to the development version later this week.

**Comment by fragla** [comment]
Now added to the development version. You can install the development version from GitHub using: 

`devtools::install_github("fragla/eq5d").`

**Comment by jiro-ishida** [comment]
Amazing thanks so much for this!
