### ISSUE TITLE
Vectorise EQ5D functions?

### ISSUE THREAD

**Issue by TimTaylor** [fragla/eq5d#19]
Would you be interested in allowing the `eq5d5l()`, `eq5d3l()` and `eq5dy()` functions to take vector inputs for the country and or type? 

Pros - makes it easier for users to compare results across countries.
Cons - more code burden when users could just use `mapply()`.

Happy to submit a PR if of interest.

**Comment by fragla** [comment]
So would this be calculating index scores for multiple countries from a single set of dimensions or five digit score? My initial thought is not to implement it in these functions given it could be easily coded. An alternative could be to code it in the `eq5d()` wrapper function given that's where the logic for processing multiple scores/five digit scores etc is.

**Comment by TimTaylor** [comment]
> So would this be calculating index scores for multiple countries from a single set of dimensions or five digit score?

Yes

> My initial thought is not to implement it in these functions given it could be easily coded. An alternative could be to code it in the `eq5d()` wrapper function given that's where the logic for processing multiple scores/five digit scores etc is.

My mistake - I meant within the `eq5d()` function. Yes - it is relatively easy to code so it is probably just adding more maintenance overhead than it is worth.

**Comment by fragla** [comment]
Yes, I've had another look at the `eq5d()` function. Given there is a relatively straightforward solution I don't think it's worth it.
