### ISSUE TITLE
Suggest adding new index value data for EQ-5D-Y?

### ISSUE THREAD

**Issue by rochellesun** [fragla/eq5d#20]
EuroQol published a new set of EQ-5D-Y value sets for Spain in April 2021. 

https://eq-5dpublications.euroqol.org/download?id=0_99118&fileId=101079

**Comment by fragla** [comment]
The EQ-5D-Y value set for Spain is in v0.11.0 pushed to CRAN yesterday. Not all of the binaries have been built (it normally takes a couple of days for CRAN to do this) so you may have to install the package from source using `install.packages("eq5d", type="source")` or from GitHub using `devtools::install_github("fragla/eq5d")`. Both methods will currently install the same version of the package.

**Comment by rochellesun** [comment]
Thank you for the impressively quick update!
