### ISSUE TITLE
Danish value set for the EQ-5D-5L - Documentation

### ISSUE THREAD

**Issue by trxtrbd** [fragla/eq5d#22]
Can you please provide documentation on the version of the value set used in this package.
I am using the eq5d packages from Cran. And I am using eq5d(scores.df, country="Denmark", version="5L", type="VT", ignore.invalid=TRUE)

I dont get the same result from this packages as I get if I use the value set from https://euroqol.org/

ie
eq5d packages from Cran
STATE 45541
> eq5d5l(scores=c(MO=4,SC=5,UA=5,PD=4,AD=1), country="Denmark")
[1] 0.079

eq5d from
https://euroqol.org/eq-5d-instruments/eq-5d-5l-about/valuation-standard-value-sets/crosswalk-index-value-calculator/
STATE 45541
0.276

This might be because the eq5d package use the new (2021) eq5d5l value set (https://pubmed.ncbi.nlm.nih.gov/34847818/)
And the set from https://euroqol.org/ is a crosswalk .

But can you please confirm this. I cant find it in the package documentation.

**Comment by fragla** [comment]
Using `eq5d(scores.df, country="Denmark", version="5L", type="VT", ignore.invalid=TRUE)` will use the 2021 EQ-5D-5L value set. If you want to use the crosswalk value set then you need to change the type to:

`eq5d(scores.df, country="Denmark", version="5L", type="CW", ignore.invalid=TRUE)`, which will give a score of 0.276 for the state 45541. 

You can view the different value sets available for a country using the `valuesets` command e.g `valuesets(country = "Denmark")`. You can also view the source of the value set using `?VT`, `?CW`, `?TTO` etc. I'm also in the process of adding PubMed identifiers and DOIs to the results of the `valuesets` command. I hope that helps?

**Comment by trxtrbd** [comment]
Thank you for the fast respond. That helped, a lot.
Thank You.
// F
