### ISSUE TITLE
Calculation discrepancy for EQ-5D-5L score 11111

### ISSUE THREAD

**Issue by fpinckaers** [fragla/eq5d#23]
I noticed that the constant is not subtracted for health state 11111 in the 5L Dutch VT, resulting in a utility of 1 (instead of 0.953). 
For all other EQ-5D-5L scores, the constant is subtracted correctly.

**Comment by fragla** [comment]
My understanding is that the constant is not used for the 11111 state. The 2016 Value in Health paper states the range of this value set as being "from -0.446 for state 55555 to 1 for state 11111".
