### ISSUE TITLE
EQ5d package: subgroup analysis issue

### ISSUE THREAD

**Issue by shoaibraees** [fragla/eq5d#26]
Thanks for the awesome EQ5D package. 
We are facing hiccups in sub-groups analysis and the use of "by" to have subgroup outputs (it is not working for either of the functions such as eq5dcf, pchc, ps, hpg etc). 
We realize an example for eq5dds function is given. But that too won't work if we try to pipe data. Please see you can provide any guidance. Thanks a lot!

**Comment by fragla** [comment]
Advice given to @shoaibraees on how to use the eq5d package for his analyses.
