### ISSUE TITLE
Add Swedish value set for EQ-5D-5L

### ISSUE THREAD

**Issue by eribul** [fragla/eq5d#4]
Thanks for a great package!

New Swedish value sets (VAS and TTO) have been published for EQ-5D-5L:
https://link.springer.com/article/10.1007%2Fs40273-020-00905-7

It would be great to see those implemented in the package :-)
Please let me know if I could help (PR or similar)!

**Comment by eribul** [comment]
See table 8 for relevant values;
https://link.springer.com/article/10.1007/s40273-020-00905-7/tables/9

**Comment by fragla** [comment]
Hi Erik

Thanks for letting me know about this. I've added the TTO one to the package and pushed to GitHub.

**Comment by eribul** [comment]
Very nice, thanks :-)
