### ISSUE TITLE
Improvement ratio

### ISSUE THREAD

**Issue by eribul** [fragla/eq5d#5]
This article:
http://ejpch.org/ejpch/article/view/1000
describes an "improvement ratio" to use with EQ-5D.
Some R functions implementing this ratio are found here:
https://github.com/eribul/eqcw/blob/master/R/ir.R
(We planned to provide a CRAN package but never did.)
If you think those functions might be relevant to your package, feel free to include them (I might assist with a PR).

**Comment by fragla** [comment]
Can you provide the PDF of the paper? I was unable to download it from the link.

Thanks!
________________________________
