### ISSUE TITLE
Suggest warning for unnamed vector to `eq5d5l`

### ISSUE THREAD

**Issue by eribul** [fragla/eq5d#6]
We tried:

```r
> eq5d5l(c(MO=3,SC=4,UA=5,PD=4,AD=3), "Sweden")
[1] 0.503
> eq5d5l(c(3, 4, 5, 4,3), "Sweden")
[1] 0.973
```

The first case is correct and is also used as one of the test cases (testthat/test-eq5d5l.R line 145).
The second case is caused by missing vector names. This might be expected since the documentation clearly states that the vector should have names. 
It might be confusing however if this detail has been overlooked, wherefore the value "0.503" would be expected.

Can I suggest an error message if names are missing (or at least a warning)?
Or if possible, that a default order of the arguments are assumed even though names might be missing.

**Comment by fragla** [comment]
Thanks for flagging. There was an error check to look if the dimension names were present in the code, but it wasn't working. This is now fixed and unit tests have been added. It's been pushed to GitHub. I'll look into assuming a default order of arguments.
