### ISSUE TITLE
alternative eq-5d-5l mapping function

### ISSUE THREAD

**Issue by bitowaqr** [fragla/eq5d#8]
Have you considered implementing the alternative value/mapping function for the UK EQ-5D-5L value set by Hernandez? 
Paper: https://www.sciencedirect.com/science/article/pii/S0167629616305070
A stata command seems to be available: https://eprints.whiterose.ac.uk/124872/8/st0528.pdf

**Comment by fragla** [comment]
Yes, it’s on the to do list. I've looked at the Stata version previously and it seemed like it would be relatively straightforward to implement in R. I just need to set some time aside to do it.

**Comment by bitowaqr** [comment]
If you send me the actual Stata file and some instructions on how you would like to see this being implemented I'd be happy to help – I need to use the mapping in a project now anyway.

**Comment by bitowaqr** [comment]
They have now released an R function:
http://nicedsu.org.uk/mapping-eq-5d-5l-to-3l/

I'd be happy to help with the implementation, but I am not sure if/how you want to integrate this in the package.

**Comment by TimTaylor** [comment]
Equally happy to help with code review if at all useful. Guess this would want #11 at same time

**Comment by fragla** [comment]
I’ll take a look at the code, but happy to hear any thoughts on the best way of implementing. 

#11 is underway, but I need to sort out the non-standard references e.g. Ecuador 3L (published by Ecuadorian Ministry of Health) and Belgium 5L (Government doc, but has an ISSN). I also need to speak with EuroQol about the reverse cross-walk value sets, which seem to have disappeared from their website.

**Comment by TimTaylor** [comment]
@fragla I like the way you've been able to standardise the implementations so hopefully it will fit in the same (not dug in to it say though)!

**Comment by fragla** [comment]
@TimTaylor @bitowaqr I've just merged my eq5dmap branch into master. It's best run in a similar way to the other methods via eq5d wrapper function (see "EQ-5D-5L to EQ-5D-3L NICE DSU mapping" in the README and also unit tests for examples). Additional arguments needed are age, sex and bwidth (if approx index score). Also works with data.frames if columns are defined. Any thoughts/ideas/criticisms welcomed.

**Comment by TimTaylor** [comment]
Cool. Will take a look when I get a moment.

**Comment by fragla** [comment]
Closing issue as implemented in release [v0.11.0](https://github.com/fragla/eq5d/releases/tag/v0.11.0).
