### ISSUE TITLE
Error if package not fully loaded

### ISSUE THREAD

**Issue by TimTaylorW** [fragla/eq5d#9]
Due to use of `get` you cannot use this package without loading the entire package (e.g. you cannot use `::` )
``` r
scores <- c(MO=1,SC=2,UA=3,PD=2,AD=1)
eq5d::eq5d(scores=scores, country="UK", version="3L", type="TTO")
#> Error in get(type): object 'TTO' not found
```

<sup>Created on 2021-09-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I suspect this is what #7 was experiencing.  You may prefer to just load it as internal data, but still make user accessible with the `valuesets()` function. This can be done following https://r-pkgs.org/data.html#data-sysdata

**Comment by fragla** [comment]
I think you may be right about #7 and it probably does make sense to internalise it. Will look into doing this for the next release.
